//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HSJ_OilManager.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HSJ_OILMANAGER_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDD_OIL_DENSITY_DIALOG          129
#define IDD_OIL_PRICE_DIALOG            130
#define IDD_SHIP_MANAGE_DIALOG          131
#define IDC_BTN_PERSON                  1000
#define IDC_BTN_SHIP                    1001
#define IDC_BTN_COMPANY                 1002
#define IDC_GB_OTHERS                   1003
#define IDC_GB_OIL                      1004
#define IDC_BTN_OIL_DENSITY             1005
#define IDC_LABEL_OIL_CALC              1006
#define IDC_BTN_OIL_PRICE               1007
#define IDC_LABEL_OIL_CALC2             1008
#define IDC_OIL_TYPE                    1009
#define IDC_OIL_DENSITY_LISTCONTROL     1010
#define IDC_COMPANY_ID_COMBO            1011
#define IDC_DENSITY_COMPANY_ID_COMBO    1011
#define IDC_PRICE_ADD_BTN               1011
#define IDC_OIL_TYPE_COMBO              1012
#define IDC_DENSITY_OIL_TYPE_COMBO      1012
#define IDC_COMPANY_LABEL               1013
#define IDC_DENSITY_COMPANY_LABEL       1013
#define IDC_OIL_TYPE_LABEL              1014
#define IDC_DENSITY_OIL_TYPE_LABEL      1014
#define IDC_COMPANY_NAME_LABEL          1015
#define IDC_COMPANY_NAME_CONTENT_LABEL  1015
#define IDC_DENSITY_COMPANY_NAME_CONTENT_LABEL 1015
#define IDC_OIL_TYPE_CONTENT_LABEL      1016
#define IDC_DENSITY_OIL_TYPE_CONTENT_LABEL 1016
#define IDC_MAIN_REFRESH                1017
#define IDC_DENSITY_ADD_BTN             1018
#define IDC_DENSITY_DETAIL_GROUPBOX     1019
#define IDC_DENSITY_DELETE_BTN          1020
#define IDC_DENSITY_LOAD_BTN            1021
#define IDC_DENSITY_LOAD_STATUS_LABEL   1022
#define IDC_DENSITY_EDIT_BTN            1023
#define IDC_DENSITY_DETAIL_ID_LABEL     1024
#define IDC_DENSITY_DETAIL_ID_EDIT      1025
#define IDC_DENSITY_DETAIL_SUMMER_LABEL 1026
#define IDC_DENSITY_DETAIL_SUMMBER_EDIT 1027
#define IDC_DENSITY_DETAIL_WINTER_LABEL 1028
#define IDC_PRICE_LIST_GROUPBOX         1028
#define IDC_DENSITY_DETAIL_WINTER_EDIT  1029
#define IDC_PRICE_LIST_LISTCONTROL      1029
#define IDC_PRICE_DETAIL_GROUPBOX       1030
#define IDC_PRICE_EDIT_BTN              1031
#define IDC_PRICE_DEL_BTN               1033
#define IDC_PRICE_DETAIL_ID_EDIT        1034
#define IDC_PRICE_DETAIL_ID_LABEL       1035
#define IDC_PRICE_DETAIL_STIME_LABEL    1036
#define IDC_PRICE_STIME_EDIT            1039
#define IDC_PRICE_DETAIL_PRICE_LABEL    1040
#define IDC_PRICE_DETAIL_PRICE_EDIT     1041
#define IDC_PRICE_LOAD_BTN              1042
#define IDC_PRICE_LOAD_STATUS_LABEL     1043
#define IDC_PRICE_OIL_TYPE_LABEL        1044
#define IDC_PRICE_OIL_TYPE_COMBO        1045
#define IDC_PRICE_OIL_TYPE_CONTENT_LABEL 1046
#define IDC_SHIP_MARINE_DEPARTMENT_GROUPBOX 1048
#define IDC_SHIP_LIST_GROUPBOX          1049
#define IDC_SHIP_LIST_LISTCONTROL       1051
#define IDC_SHIP_DETAIL_GROUPBOX        1052
#define IDC_SHIP_ADD_BTN                1053
#define IDC_SHIP_EDIT_BTN               1054
#define IDC_SHIP_DEL_BTN                1055
#define IDC_SHIP_MARINE_DEPARTMENT_LABEL 1056
#define IDC_MARINE_DEPARTMENT_COMBO     1057
#define IDC_BUTTON4                     1058
#define IDC_SHIP_LOAD_BTN               1058
#define IDC_SHIP_LOAD_STATUS_LABEL      1059
#define IDC_SHIP_DETAIL_MMSI_EDIT       1060
#define IDC_SHIP_DETAIL_MMSI_LABEL      1061
#define IDC_SHIP_DETAIL_NAME_LABEL      1062
#define IDC_SHIP_DETAIL_NAME_EDIT       1063
#define IDC_SHIP_DETAIL_SPEED_LABEL     1064
#define IDC_SHIP_DETAIL_SPEED_EDIT      1065
#define IDC_SHIP_DETAIL_LOADWEIGHT_LABEL 1066
#define IDC_SHIP_DETAIL_LOADWEIGHT_EDIT 1067
#define IDC_SHIP_DETAIL_DRAFT_LABEL     1068
#define IDC_SHIP_DETAIL_DRAFT_EDIT      1069
#define IDC_SHIP_DETAIL_LLUNSPEED_LABEL 1070
#define IDC_SHIP_DETAIL_LLUNSPEED_EDIT  1071
#define IDC_SHIP_DETAIL_RLUNSPEED_LABEL 1072
#define IDC_SHIP_DETAIL_RLUNSPEED_EDIT  1073
#define IDC_SHIP_DETAIL_MEMO_EDIT       1074
#define IDC_SHIP_DETAIL_DEVICEID_EDIT   1075
#define IDC_SHIP_DETAIL_DEVICEID_LABEL  1076
#define IDC_SHIP_DETAIL_MEMO_LABEL      1077
#define IDC_SHIP_DETAIL_MAXGPS_LABEL    1078
#define IDC_SHIP_DETAIL_MAXGPS_EDIT     1079
#define IDC_SHIP_DETAIL_COMPANYID_LABEL 1080
#define IDC_SHIP_DETAIL_COMPANYID_COMBO 1083
#define IDC_SHIP_DETAIL_OILTYPEID_LABEL 1084
#define IDC_COMBO3                      1085
#define IDC_SHIP_DETAIL_OILTYPEID_COMBO 1085

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
